---
- name: Configure hosts & deploy application # <-- description
  hosts: all # <-- to which hosts will be performed task
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.18
  tasks: # <-- block of tasks that will be performed for these hosts
    - name: Change mongo config file
      become: true # <-- run as root
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644 # <-- file permissions to install
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy: 
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ivanmazur/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
    
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ivanmazur/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma
    
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ivanmazur/reddit # <-- in which directory execute the command
      tags: deploy-tag
      
  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted

    # handler which systemd will indicate that the unit for the service has changed and should by re-read
  - name: reload puma
    become: true
    systemd: name=puma state=restarted